### ISSUE TITLE
Issue trying it out locally

### ISSUE THREAD

**Issue by mstfash** [borisno2/on-the-hill-drama-club#120]
Hey Great job open sourcing this, it is really cool!

I have got an issue trying this locally, added some env variables to help running everything and changed the database url and everything however, my sole issue here is I get I go to `http://localhost:4000/admin`, I get 
```
Unhandled Runtime Error
Error: An error occurred when loading Admin Metadata
```

Here is a screenshot that shows the error, tried visiting keystone github repo but had no chance solving this issue.

Have you ever faced this issue? or could you help me out try to figure out what is going on ? Thanks in advance and again great work!

![Screen Shot 2023-07-19 at 6 18 57 AM](https://github.com/borisno2/on-the-hill-drama-club/assets/5751607/33d45e93-a902-4bb8-87e3-14ad5bf8a36d)

**Comment by borisno2** [comment]
Hi @mstfash glad you can find the project useful!

You will need to access the admin UI through the port that the nextjs site is running on (default `http://localhost:3000/admin` you need to have both the frontend and keystone running at the same time, this is because the Admin UI uses the Graphql API served from the Frontend next app.
